this is the way task
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-OdelyaTick22 pull request #1
Opened 2022-03-24 14:55 UTC by OdelyaTick22

2022-03-25 18:54 UTC, talbarfm requested changes

2022-03-25 18:54 UTC, talbarfm commented on ThisIsTheWay.py
> +
Add an example of the code execution

2022-03-25 18:54 UTC, talbarfm commented on ThisIsTheWay.py
> +    for name in arr:
you can reduce this whole function to be a one linse

2022-03-25 18:54 UTC, talbarfm commented on ThisIsTheWay.py
> +def way(path):
use type hints and return types

2022-03-25 18:54 UTC, talbarfm commented on ThisIsTheWay.py
> +def way(path):
document

2022-03-30 08:30 UTC, lovodkin93 requested changes

2022-03-30 08:30 UTC, lovodkin93 commented on ThisIsTheWay.py
> +"""
write the example in a "main"

2022-04-24 12:00 UTC, merged